### ISSUE TITLE
resnet

### ISSUE THREAD

**Issue by danmlevi** [shirgur/AGFVisualization#1]
Amazing work Shir!
When I try using a resnet model  in the example:
model = resnet18(pretrained=True).to(device)
I get the following error:

Traceback (most recent call last):
  File "/home/kzfm0t/code/visualization/AGFVisualization-master/example.py", line 97, in <module>
    dog = get_visualization(out)
  File "/home/kzfm0t/code/visualization/AGFVisualization-master/example.py", line 73, in get_visualization
    return model.AGF(**kwargs)
  File "/home/kzfm0t/code/visualization/AGFVisualization-master/modules/resnet.py", line 227, in AGF
    cam, grad_outputs = self.layer4.AGF(cam, grad_outputs, **kwargs)
  File "/home/kzfm0t/code/visualization/AGFVisualization-master/modules/layers.py", line 428, in AGF
    cam, grad_outputs = m.AGF(cam, grad_outputs, **kwargs)
  File "/home/kzfm0t/code/visualization/AGFVisualization-master/modules/resnet.py", line 82, in AGF
    return self.clone.AGF((cam, cam2), grad_outputs + grad_outputs2)
TypeError: add(): argument 'other' (position 1) must be Tensor, not tuple

Process finished with exit code 1
Couldn't fix it immediately by making it a 2-tupple

**Comment by shirgur** [comment]
Thank you,
Please use ResNet50 for now
